import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [snippetText, setSnippetText] = useState('');
  const router = useRouter();

  const snippet = trpc.useMutation(["snippet.saveSnippet"]);

  const handleSaveSnippet = async () => {
    const newlyCreatedSnippet = await snippet.mutateAsync({
      text: snippetText
    })
    router.push(`/snippets/${newlyCreatedSnippet.id}`);
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 gap-4">
        Paste Bin Clone

        <p>
          Feel free to paste in a snippet of text or code and you will get back a unique UIUD to view at any time
        </p>
        <textarea className="border p-2 w-1/3 h-48" value={snippetText} onChange={e => setSnippetText(e.target.value)}>

        </textarea>

        <button onClick={handleSaveSnippet} className="p-2 text-white rounded bg-blue-500 hover:bg-blue-400">Save Snippet</button>
      </main>
    </>
  );
};

export default Home;
