import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [snippetText, setSnippetText] = useState("");
  const router = useRouter();

  const snippet = trpc.useMutation(["snippet.saveSnippet"]);

  const handleSaveSnippet = async () => {
    const newlyCreatedSnippet = await snippet.mutateAsync({
      text: snippetText,
    });
    router.push(`/snippets/${newlyCreatedSnippet.id}`);
  };

  return (
    <>
      <Head>
        <title>PasteBinClone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 gap-4">
        <h1 className="text-4xl">Paste Bin Clone</h1>

        <p className="">
          Paste in your snippet and you will get a link to send to all your friends!
        </p>
        <textarea
          className="border border-grey-600 rounded-md p-3 w-2/4 h-screen/2"
          placeholder="e. g. Hello"
          value={snippetText}
          onChange={(e) => setSnippetText(e.target.value)}
        ></textarea>

        <button
          onClick={handleSaveSnippet}
          className="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 w-72"
        >
          Save Snippet
        </button>
      </main>
    </>
  );
};

export default Home;
