import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { useOrigin } from "../../hooks/useOrigin";
import { trpc } from "../../utils/trpc";

const SnippetPage = () => {
  const router = useRouter();
  const id = router.query.id as string;
  const snippets = trpc.useQuery([
    "snippet.getSnippet",
    {
      id,
    },
  ]);

  const handleCopyToClipboard = () => {
    if (!snippets.data) return;
    navigator.clipboard.writeText(snippets.data.text);
  };

  const origin = useOrigin();
  
  return (
    <>
      <Head>
        <title>PasteBinClone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 gap-4">
        <h1 className="font-bold text-4xl">Viewing A Snippet</h1>
        <p>Feel free to <a className="underline text-blue-600 hover:text-blue-800 visited:text-purple-600" href={`${origin}`}>create a new snippet</a></p>
        <Link href={`/snippets/{id}`}>
                {`${origin}/snippets/${id}`}
        </Link>
        <textarea
          className="border border-grey-600 rounded-md p-3 w-2/4 h-screen/2"
          disabled
          value={snippets.data?.text}
        ></textarea>
        <button
          className="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 w-72"
          onClick={handleCopyToClipboard}
        >
          Copy Snippet to Clipboard
        </button>
      </div>
    </>
  );
};

export default SnippetPage;
